/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#625d5b",
        "surface": "#fdf8f7",
        "background": "#fdf8f7",
        "on-secondary-fixed": "#002117",
        "on-error-container": "#93000a",
        "surface-container": "#f1edec",
        "surface-bright": "#fdf8f7",
        "error-container": "#ffdad6",
        "secondary": "#2b6954",
        "surface-container-low": "#f7f3f1",
        "secondary-fixed": "#b0f0d6",
        "inverse-surface": "#313030",
        "on-error": "#ffffff",
        "tertiary": "#000000",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#ccc5c2",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-fixed-variant": "#454747",
        "on-surface": "#1c1b1b",
        "primary": "#000000",
        "outline-variant": "#d0c4be",
        "surface-dim": "#ddd9d8",
        "outline": "#7e7570",
        "surface-variant": "#e6e1e0",
        "surface-container-highest": "#e6e1e0",
        "primary-fixed": "#e9e1dd",
        "on-tertiary-fixed": "#1a1c1c",
        "on-surface-variant": "#4d4540",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#4a4643",
        "on-primary-fixed": "#1e1b19",
        "secondary-fixed-dim": "#95d3ba",
        "secondary-container": "#adedd3",
        "on-secondary-container": "#306d58",
        "on-tertiary-container": "#838484",
        "on-primary-container": "#888380",
        "primary-container": "#1e1b19",
        "inverse-primary": "#ccc5c2",
        "inverse-on-surface": "#f4f0ef",
        "tertiary-container": "#1a1c1c",
        "tertiary-fixed-dim": "#c6c6c6",
        "surface-container-high": "#ece7e6",
        "on-secondary-fixed-variant": "#0b513d",
        "on-background": "#1c1b1b",
        "on-secondary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-md": "48px",
        "container-max": "1440px",
        "stack-sm": "24px",
        "unit": "4px",
        "stack-lg": "80px",
        "margin-mobile": "20px",
        "gutter": "32px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "headline-md": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["40px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "display-lg": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "display-lg-mobile": ["48px", { "lineHeight": "1.15", "fontWeight": "700" }],
        "headline-sm": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "label-sm": ["13px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
